const cartConstants = {
    FETCH_CART_REQUEST:"FETCH_CART_REQUEST",
    FETCH_CART_SUCCESS:"FETCH_CART_SUCCESS",
    FETCH_CART_FAILURE:"FETCH_CART_FAILURE",
    ADD_CART:"ADD_CART",
    "REMOVE_CART":"REMOVE_CART",
    "INCREASE_QUANTITY":"INCREASE_QUANTITY",
    "DECREASE_QUANTITY":"DECREASE_QUANTITY"
}
export default cartConstants;